### ISSUE TITLE
Issues compiling with OpenFoam 4.1

### ISSUE THREAD

**Issue by fbisetti** [acuoci/laminarSMOKE#11]
Hi Alberto:

I am having difficulties compiling laminarSMOKE with OpenFOAM 4.1. The issue pertains to both laminarPimpleSMOKE and laminarSimpleSMOKE. I discuss the latter only.

Note that the rest of the solvers (i.e. laminarBuoyantPimpleSMOKE, laminarBuoyantSimpleSMOKE, and laminarSMOKEpostProcessor) compile correctly.

The compilation fails on solvers/laminarSimpleSMOKE as below.

It seems that laminarSimpleSMOKE.C requires pressureControl.H, which is available in OpenFoam-dev, but not in 4.1

g++ -std=c++0x -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -DOPENFOAM_VERSION=40 -w -DOPENSMOKE_USE_MKL=0 -DOPENSMOKE_USE_ISAT=0 -DDEVVERSION=0  -I../laminarSMOKE -I../laminarSMOKE/steady -I../../libs/radiationOpenSMOKE++/lnInclude -I../openSMOKEpp4laminarSMOKE/ -I/usr/lib64/include -I/usr/include/eigen3 -I/home/fbisetti/OpenFOAM/thirdparty-polimi/rapidxml-1.13 -I/include -I/include -I/ -I/apps/openfoam/4.1/gcc/system/openmpi-2.1.0/OpenFOAM-4.1/src/finiteVolume/lnInclude -I/apps/openfoam/4.1/gcc/system/openmpi-2.1.0/OpenFOAM-4.1/src/fvOptions/lnInclude -I/apps/openfoam/4.1/gcc/system/openmpi-2.1.0/OpenFOAM-4.1/src/meshTools/lnInclude -I/apps/openfoam/4.1/gcc/system/openmpi-2.1.0/OpenFOAM-4.1/src/sampling/lnInclude -I/apps/openfoam/4.1/gcc/system/openmpi-2.1.0/OpenFOAM-4.1/src/thermophysicalModels/basic/lnInclude -IlnInclude -I. -I/apps/openfoam/4.1/gcc/system/openmpi-2.1.0/OpenFOAM-4.1/src/OpenFOAM/lnInclude -I/apps/openfoam/4.1/gcc/system/openmpi-2.1.0/OpenFOAM-4.1/src/OSspecific/POSIX/lnInclude   -fPIC -c laminarSimpleSMOKE.C -o Make/linux64GccDPInt32Opt/laminarSimpleSMOKE.o
laminarSimpleSMOKE.C:66:30: fatal error: pressureControl.H: No such file or directory
  #include "pressureControl.H"
                              ^
compilation terminated.
make: *** [Make/linux64GccDPInt32Opt/laminarSimpleSMOKE.o] Error 1

I am not sure how to fix this!

Thanks
Fabrizio

**Comment by acuoci** [comment]
Dear Fabrizio,
yes, you are right, there is a bug in the code: pressureControl.H is available in OpenFoam-dev, but not in 4.1. I fixed the bug and uploaded on github the corrected version. Please let me know if everything works correctly.
Thank you very much,
A
