### ISSUE TITLE
Compiling the solver

### ISSUE THREAD

**Issue by mahesh1463** [acuoci/laminarSMOKE#14]

**Comment by mahesh1463** [comment]
Hello prof,

Am very much interested in laminar transient solution. 
Am following your steps to run the solver

when am compiling the solver a lot of errors are coming, where am not able to understand. Could you please briefly tell us to compile.

**Comment by acuoci** [comment]
Dear Mahesh,
please consider that the "Issues" section is to report possible bugs in the code, not to give instructions on how to compile/install the code. 
Thus, if you think there is bug, please open a new issue, by reporting all the relevant details about the error you are experinciencing, so I can reproduce it.
Best regards,
Alberto
