### ISSUE TITLE
How to Download OpenSMOKE++

### ISSUE THREAD

**Issue by 21071997** [acuoci/laminarSMOKE#16]

**Comment by 21071997** [comment]
Dear Profesor Alberto  Cuoci,
![Screenshot (16)](https://user-images.githubusercontent.com/48725624/54617615-973e6580-4a87-11e9-9baf-8d28c2962493.png)

Sir, I am working on Coflowing Methane/Biogas flames for which I am trying to use LaminarSmoke. Sir, I am new to both OpenFOAM and the field of Combustion.

In the procedure which you described on Github(https://github.com/acuoci/laminarSMOKE). In this how to download OpenSmoke + +??. I just downloaded the code from Github and downloaded and installed Rapid XML, BoostC++ and Eigen libraries. Then by following all the instructions, I came to compiling stage when I am trying to compile boundary_condition using wmake it is showing this error( in the attached file). 
I am using OpenFOAM 4.0 and Ubuntu 14.04.


Thanks in advance

**Comment by acuoci** [comment]
1. As clearly reported in the README file, OpenSMOKE++ is provided with laminarSMOKE, so there is no need to download it from external sites.
2. The error message reported in the screenshot is not about laminarSMOKE, but about OpenFOAM. It seems it is not installed properly. Please consider that laminarSMOKE requires a good knowledge of OpenFOAM framework and Linux environment in general.
3. Please, do not use GitHub for private communications, but only for messages about bugs and issues with laminarSMOKE.
